### ISSUE TITLE
Preservation of file modification time not reliable

### ISSUE THREAD

**Issue by martinburger** [mostafah/fsync#4]
As described in issue spf13/hugo#1054, preservation of file modification time is not reliable in some cases.

When running `hugo`, for some files the modification time is synchronized during the second run only:

```
$ rm -rf public
$ ls -lart@ static/test
-rw-r--r--  1 mburger  staff       0  1 Jan  2014 somefile
-rw-r--r--  1 mburger  staff       0  3 Apr 18:53 someotherfile
-rw-r-----  1 mburger  staff  295061  3 Apr 18:53 some.pdf
drwxr-xr-x  5 mburger  staff     272  7 Apr 07:07 ..
drwxr-xr-x  2 mburger  staff     170  7 Apr 07:17 .
$ hugo --noTimes=false
[...]
$ ls -lart@ public/test
-rw-r--r--   1 mburger  staff       0  1 Jan  2014 somefile
-rw-r--r--   1 mburger  staff       0  3 Apr 18:53 someotherfile
drwxr-xr-x   2 mburger  staff     170  7 Apr 07:17 .
-rw-r-----   1 mburger  staff  295061  7 Apr 19:45 some.pdf
drwxr-xr-x  11 mburger  staff     612  7 Apr 19:45 ..
$ hugo --noTimes=false
[...]
$ ls -lart@ public/test
-rw-r--r--   1 mburger  staff       0  1 Jan  2014 somefile
-rw-r--r--   1 mburger  staff       0  3 Apr 18:53 someotherfile
-rw-r-----   1 mburger  staff  295061  3 Apr 18:53 some.pdf
drwxr-xr-x  11 mburger  staff     612  7 Apr 07:07 ..
drwxr-xr-x   2 mburger  staff     170  7 Apr 07:17 .
```

As you can see, file `some.pdf` gets the original modification time on the second run only.

This might be an issue with the underlying fsync library.

**Comment by mostafah** [comment]
I didn’t find any reference to this package in Hugo. Am I missing something here?

**Comment by martinburger** [comment]
Good catch! Well, Hugo uses package `github.com/spf13/fsync` (see: [hugo.go#L29](https://github.com/spf13/hugo/blob/bebb1b9d5dfc629ec73c4d3dbdb71ac15400ff3a/commands/hugo.go#L29)).

[That package](https://github.com/spf13/fsync) is forked from `mostafah/fsync`. Should I report this issue there?

**Comment by mostafah** [comment]
I see. So, that’s what I was missing. I’ll look into it soon.

**Comment by martinburger** [comment]
I just realized that they added support for "Afero - A FileSystem Abstraction System for Go" in commit [1fdf08f](https://github.com/spf13/fsync/commit/1fdf08f822b05e59a6515ee151b683c3a02efea5) which brings their version 1 commit ahead of yours. As far as I understand that change, they might have forgotten to adapt ["update dst's modification time"](https://github.com/spf13/fsync/blob/master/fsync.go#L213).

**Comment by mostafah** [comment]
Seem like you’re right. They’ve updated all the FS-related calls with Afero equivalents, except for this line:

    err := os.Chtimes(dst, sstat.ModTime(), sstat.ModTime())

I’m not sure how this works after the first run, but then again I don’t know anything about Afero.

So this is no longer an issue here. Right?

**Comment by martinburger** [comment]
Right, I accordingly updated spf13/hugo#1054.

**Comment by mostafah** [comment]
Thanks for taking care of most of the work here.
