### ISSUE TITLE
Fwd: FTBFS: TestSync is overly sensitive about mtimes

### ISSUE THREAD

**Issue by anthonyfok** [mostafah/fsync#5]
Hello @mostafah,

The folks at Debian did a bunch of automated builds under various conditions to assert they are "reproducible", and discovered that **fsync**'s TestSync test would fail randomly, as reported in the Debian Bug Tracking System as "FTBFS" (Fail To Build From Source) at https://bugs.debian.org/802340.

There seems to be two *separate* problems in the Debian bug report.  One is that the modification time for "dst" is occasionally off by milliseconds:

```
=== RUN TestSync
--- FAIL: TestSync (0.01s)
	fsync_test.go:136: modification time for "dst" is 2015-10-18 17:53:51.170102485 +0000 UTC, should be 2015-10-18 17:53:51.166102492 +0000 UTC.
FAIL
```

And the second is off by one hour:

```
    fsync_test.go:136: modification time for "dst/a/b" is 2015-10-17 16:23:22.048 +0000 UTC, should be 2015-10-17 15:23:22.051578088 +0000 UTC.
    fsync_test.go:136: modification time for "dst/c" is 2015-10-17 16:23:22.048 +0000 UTC, should be 2015-10-17 15:23:22.051578088 +0000 UTC.
```

Even though the Debian bug report was filed against the spf13/fsync fork, I was able to reproduce the first problem (off by milliseconds) in your original mostafah/fsync like this:

```
cd $GOPATH/src/github.com/mostafah/fsync
go test -c
./fsync.test -test.count 1000
```

Out of the consecutive 1000 runs, I would get about 100 FAILs.  If it doesn't show for you, try increasing `-test.count` to 5000 or even 10000, and perhaps keep your system busy with other things, and I think you will be able to reproduce it.  On my computer, I was able to reproduce it with both ext4 and tmpfs (i.e. filesystem in RAM), so I think it is filesystem agnostic.

Meanwhile, I think the second problem (mtime off by one hour or so) **might** be related to #4 (hence spf13/hugo#1054) and thus only reproducible in spf13/fsync.  I haven't been able to reproduce this off-by-one-hour issue in either mostafah/fsync or spf13/fsync yet.

Many thanks in advance!  :-)

Cheers,
Anthony

Cc: @spf13, @bep, @martinburger re: spf13/hugo#1054

**Comment by mostafah** [comment]
Thanks for the report. It’s a bug. I should have considered that the tests themselves might take a few milliseconds to run. I’ll look into it and try to fix it.

You are probably right about the second problem being related to Afero, but please let me know if it turned out to be happening with my version too.

**Comment by mostafah** [comment]
I found the root of the issue: I had completely ignored the fact that changing contents of a directory changes its `mtime` to current system time.

Here’s what happens that leads to this error: directory `dst` is created and its `mtime` is set to that of `src`, but then the code starts writing contents of `dst` and that changes its `mtime`. In other words, `mtime` for directories was not being synced at all.

The funny part is that I was wise enough to change `mtime`s of source files and directories in the test code to the past to make sure they are actually synced, but stupid enough to do it this way:

```go
// set times in the past to make sure times are synced, not accidentally
// the same
tt := time.Now().Add(-1 * time.Hour)
check(os.Chtimes("src/a", tt, tt))
check(os.Chtimes("src/a/b", tt, tt))
check(os.Chtimes("src/c", tt, tt))
```

That’s why this bug was not caught easily with normal tests: the `mtime`s of directories was actually set to current time because of these `Chtimes` calls on their children. I’ve changed this part to this:

```go
// set times in the past to make sure times are synced, not accidentally
// the same
tt := time.Now().Add(-1 * time.Hour)
check(os.Chtimes("src/a/b", tt, tt))
check(os.Chtimes("src/a", tt, tt))
check(os.Chtimes("src/c", tt, tt))
check(os.Chtimes("src", tt, tt))
```

This correctly changes `mtime`s of all the source files and directories to an hour ago and thus the test now detects the bug and fails every time; i.e., without `-test.count 1000`.

I still haven’t thought of how to change `mtime` sync to fix this problem, but I have to get to other works today and postpone this for another time.

BTW, that second problem probably has something to do with this “one hour ago” trick of the test code.

**Comment by anthonyfok** [comment]
Many thanks for looking into this issue in such depth.  No hurries about fixing this issue: I will rebuild the Debian package to basically `go test || :` to ignore any errors, until the issue is resolved at your end.  So, please take your time.  :-)

Meanwhile, do you think it would be a good idea to change the "one hour ago" trick to something like "three hours ago" trick to make it easier to determine whether the second problem has to do with the "one hour ago" trick or daylight saving time?  Many thanks!  :-)

**Comment by mostafah** [comment]
Thanks. Sure, that makes sense. I can do that one in a minute. Do you want that now or along with the other changes?

**Comment by anthonyfok** [comment]
No worries, I have already uploaded a new version changing "one hour ago" to "three hours ago", and this new version is now in Debian:

```
golang-github-spf13-fsync (0.0~git20141101.0.1fdf08f-2) unstable; urgency=high

  * Prevent a minor mtime discrepancy in TestSync (go test) from triggering
    a FTBFS.  Thanks Chris Faux!  (Closes: #802340)
  * Add a temporary patch to change the "one hour ago" trick to "three hours
    ago" to see how the buildlog would change on reproducible.debian.net
  * Change "MIT" to "Expat" in debian/copyright

 -- Anthony Fok <foka@debian.org>  Tue, 10 Nov 2015 15:56:36 -0700
```

And you are right!  The "one hour ago" or "three hours ago" trick does have something to do with it!  The modification times are now off by three hours:

```
=== RUN   TestSync
--- FAIL: TestSync (0.00s)
	fsync_test.go:136: modification time for "dst/a/b" is 2015-11-11 06:22:06.590528297 +0000 UTC, should be 2015-11-11 03:22:06.592643169 +0000 UTC.
	fsync_test.go:136: modification time for "dst/c" is 2015-11-11 06:22:06.590528297 +0000 UTC, should be 2015-11-11 03:22:06.592643169 +0000 UTC.
FAIL
exit status 1
```

The full buildlog is available at:

https://reproducible.debian.net/logs/unstable/amd64/golang-github-spf13-fsync_0.0~git20141101.0.1fdf08f-2.build2.log.gz

Not exactly sure why though.  Strange environment variable?  Underlying filesystem?  Afero related or not?  Hard to say.

**Comment by mostafah** [comment]
It’s a good thing that we now know more about that second bug too. I have to think more about it.

**Comment by anthonyfok** [comment]
It might have to do with the decidedly eccentric setup of the build environment that Debian intentionally use, as seen here: https://reproducible.debian.net/reproducible.html  (the second build)
and https://reproducible.debian.net/rb-pkg/unstable/amd64/golang-github-spf13-fsync.html

I probably should try to reproduce that environment on my computer too.  Maybe some other day.  :-)

**Comment by anthonyfok** [comment]
A quick update: I was finally able to trigger the second problem (off by *n* hours):

```
   dh_auto_test -O--buildsystem=golang
	go test -v github.com/mostafah/fsync
=== RUN   TestSync
--- FAIL: TestSync (0.00s)
	fsync_test.go:136: modification time for "dst/a/b" is 2015-11-14 16:37:52.328460802 +0000 UTC, should be 2015-11-14 15:37:52.332216944 +0000 UTC.
	fsync_test.go:136: modification time for "dst/c" is 2015-11-14 16:37:52.328460802 +0000 UTC, should be 2015-11-14 15:37:52.332216944 +0000 UTC.
FAIL
exit status 1
FAIL	github.com/mostafah/fsync	0.004s
dh_auto_test: go test -v github.com/mostafah/fsync returned exit code 1
```

 inside a Debian pbuilder/cowbuilder chroot package builder environment on my own laptop with the following command:

    sudo cowbuilder --configfile pbuilderrc.rebuild \
                    --build golang-github-mostafah-fsync_0.0~git20141015.0.c6c0918-1.dsc

where the config file `pbuilderrc.rebuild` contains the line `umask 0002`.

`golang-github-mostafah-fsync_0.0~git20141015.0.c6c0918-1.dsc` (with `.orig.tar.xz` and `.debian.tar.xz`) was created by

```
dh-make-golang github.com/mostafah/fsync
cd golang-github-mostafah-fsync
dpkg-buildpackage -S
```

Other factors like locale or timezone do not matter.

The use of `umask 0002` for testing comes from `second_build()` in http://anonscm.debian.org/cgit/qa/jenkins.debian.net.git/tree/bin/reproducible_build.sh#n573, which generates a buildlog like https://reproducible.debian.net/logs/unstable/amd64/golang-github-spf13-fsync_0.0~git20141101.0.1fdf08f-2.build2.log.gz where the "off by *n* hour(s) bug" is triggered.

Note, however, that simply running `umask 0002; go test -v` (outside chroot) does not trigger this bug for me, so I will need to dig deeper.

**Comment by anthonyfok** [comment]
Wait!  The `umask 0002` trick works for me now!  Did I do something wrong before?  Or is it time-specific?  Or perhaps I was delusional?  Don't know.  :-D

```
$ umask 0022
$ go test -v github.com/mostafah/fsync
=== RUN   TestSync
--- PASS: TestSync (0.00s)
PASS
ok  	github.com/mostafah/fsync	0.003s
$ umask 0002
$ go test -v github.com/mostafah/fsync
=== RUN   TestSync
--- FAIL: TestSync (0.00s)
	fsync_test.go:136: modification time for "dst/a/b" is 2015-11-14 12:16:50.130875985 -0700 MST, should be 2015-11-14 11:16:50.133133817 -0700 MST.
	fsync_test.go:136: modification time for "dst/c" is 2015-11-14 12:16:50.130875985 -0700 MST, should be 2015-11-14 11:16:50.133133817 -0700 MST.
FAIL
exit status 1
FAIL	github.com/mostafah/fsync	0.003s
```

**Comment by bep** [comment]
I'm following this thread with great interest. With popcorn.

**Comment by anthonyfok** [comment]
> I'm following this thread with great interest. With popcorn.

Haha, good one, @ bep!  :-)

One more trivial discovery before I actually go and try to read the code:

```
$ umask 0007
$ go test -v github.com/mostafah/fsync
=== RUN   TestSync
--- FAIL: TestSync (0.00s)
	fsync_test.go:127: permissions for "dst" is -rwxr-x---, should be -rwxr-xr-x.
	fsync_test.go:127: permissions for "dst/a" is -rwxr-x---, should be -rwxr-xr-x.
	fsync_test.go:127: permissions for "dst/a/b" is -rw-r-----, should be -rw-r--r--.
	fsync_test.go:127: permissions for "dst/c" is -rw-r-----, should be -rw-r--r--.
	fsync_test.go:136: modification time for "dst/a/b" is 2015-11-14 12:33:30.566293036 -0700 MST, should be 2015-11-14 11:33:30.571906276 -0700 MST.
	fsync_test.go:136: modification time for "dst/c" is 2015-11-14 12:33:30.566293036 -0700 MST, should be 2015-11-14 11:33:30.571906276 -0700 MST.
FAIL
exit status 1
FAIL	github.com/mostafah/fsync	0.007s
```

I also played with other crazy umasks like `umask 0027`, `umask 0044`, etc. which result in similar errors.

**Comment by mostafah** [comment]
@anthonyfok Thanks for the great job. So the code was syncing `mtime`s only when the permissions were equal!

**Comment by mostafah** [comment]
It turns out it was the test code again. It was checking `mtime` on `dst` before it has been synced. The new commit fixes that, but I didn’t close the issue before you verifying this is fixed.

**Comment by anthonyfok** [comment]
@mostafah Thank you very much!  I think you have fixed all the issues discussed in this thread.  I did various tests, including setting some crazy umasks values, running the test 10000 times, and running the package through Debian reproducible tests passed with flying colours:

```
                              _            _ _     _      
 _ __ ___ _ __  _ __ ___   __| |_   _  ___(_) |__ | | ___ 
| '__/ _ \ '_ \| '__/ _ \ / _` | | | |/ __| | '_ \| |/ _ \
| | |  __/ |_) | | | (_) | (_| | |_| | (__| | |_) | |  __/
|_|  \___| .__/|_|  \___/ \__,_|\__,_|\___|_|_.__/|_|\___|
         |_|                                              
```

Thank you for your great work!

**Comment by mostafah** [comment]
Thank you for spotting the bugs. :+1: The test code was very unreliable before.

**Comment by anthonyfok** [comment]
Thank you for actually investigating and correcting the code!  That is the hard part.

As for spotting the bugs, the credit goes to the Debian Reproducible Build team who made up all these crazy corner cases in order to trigger FTBFS (fail-to-build-from-source) bugs, and the Debian infrastructure "threatening" to auto-remove such FTBFS packages from "testing" (staging area for the next Debian stable release) within a few weeks, so I was kind of forced to act... :wink:

**Comment by mostafah** [comment]
:clap:
